resources:
  - name: sample_code
    type: GitRepo
    configuration:
      path: raksha78/jfrog-pipelines-matrix-example      # Change to your own path
      branches:
        include: ^master$
      gitProvider: rak_git                      # Change to your own GitHub integration name

pipelines:
  - name: Matrix_Tutorial
    steps:
      - name: setup
        type: PreMatrix
        configuration:
          inputResources:
            - name: sample_code
        execution:
          onExecute:
            - echo "Preparing the code base"
            - pushd "${res_sample_code_resourcePath}/app"
            - npm install
            - popd 
            - mkdir -p app
            - cp -r "${res_sample_code_resourcePath}/app/." ./app/

      - name: test
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: setup
        stepletMultipliers:
          environmentVariables:
            - module: mod_1
            - module: mod_2
            - module: mod_3
            - module: mod_4
          runtimes:
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 12
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 8.17.0                    
        execution:
          onExecute:
            - pushd ./setup/app
            - MODULE="$module" npm run test
            - popd
          onComplete:
            - save_tests ./setup/app/reports  

      - name: output
        type: PostMatrix
        configuration:
          inputSteps: 
            - name: test
        execution:
          onExecute:
            - echo "Executing the output step"
            - ls -ltr ./test/setup/app/reports
            - save_tests ./test/setup/app/reports


              
