pipelines:
  - name: S_Matrix_0033
    steps:
      - name: set_up
        type: PreMatrix
        execution:
          onExecute:
            - echo "Preparing the code base"
            - npm install
            - echo "Installed npm"
      - name: matrix_3e_2r_example
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: set_up
        stepletMultipliers:
          environmentVariables:
            - animal: dog
              bird: sparrow
            - animal: cat
              bird: crow
            - animal: cow
              bird: parrot
          runtimes:
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 12
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 8.17.0    
        execution:
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
            - echo "Variation animal = ${animal}, bird = ${bird}"

          
