pipelines:
  - name: S_Matrix_0033
  steps:
      - name: matrix_3e_2r_example
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables:
            - animal: dog
              bird: sparrow
            - animal: cat
              bird: crow
            - animal: cow
              bird: parrot
          runtimes:
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 12
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 8.17.0    
        execution:
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
            - echo "Variation animal = ${animal}, bird = ${bird}"
        exclude:                   # optional, array of combinations
            - nodePool:              # that are not executed 
              environmentVariables:
                animal: dog
              runtime: 

          
